name: CI
on:
  push:
    tags:        
      - 'v*.*.*' 
  release:
    types: [ published ]
jobs:
    docker:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
          -
            name: Login to GitHub Container Registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ github.token }}
          -
              name: Build and push
              uses: docker/build-push-action@v4
              with:
                  push: true
                  platforms: linux/amd64
                  tags: |
                    ghcr.io/${{ github.repository }}:latest
                    ghcr.io/${{ github.repository }}:${{ github.ref_name }}
